/**
 * Database Types
 * This file will contain Supabase-generated types
 * Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.types.ts
 */

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[];

export interface Database {
    // TODO: Add your database schema types here
    // These will be generated by Supabase CLI
}
